package mg.miniframework.persistence.utils;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;

import mg.miniframework.persistence.annotation.Column;
import mg.miniframework.persistence.annotation.PrimaryKey;
import mg.miniframework.persistence.annotation.Table;

public class ClassUtils {

    public static String buildUpdateQueryFromClass(Class<?> clazz) {
        List<Field> fields = CGenericUtils.getAllFields(clazz);
        List<String> setClauses = new ArrayList<>();
        Field primaryKeyField = null;

        for (Field field : fields) {
            if (field.getAnnotation(PrimaryKey.class) != null && primaryKeyField == null) {
                primaryKeyField = field;
            }

            if (CGenericUtils.isFieldIgnored(field)) {
                continue;
            }
            if (CGenericUtils.isAutoGeneratedPrimaryKey(field)) {
                continue;
            }
            if (CGenericUtils.isGeneratedField(field)) {
                continue;
            }

            String columnName = getFieldName(field);
            setClauses.add(columnName + " = ?");
        }

        if (setClauses.isEmpty()) {
            throw new IllegalStateException("No updatable fields found for " + clazz.getSimpleName());
        }

        String primaryKeyColumn = (primaryKeyField != null) ? getFieldName(primaryKeyField) : "id";
        String setPart = String.join(", ", setClauses);
        return "UPDATE " + getTableName(clazz) + " SET " + setPart + " WHERE " + primaryKeyColumn + " = ?";
    }

    public static String buildInsertQueryFromClass(Class<?> clazz) {

        Field[] fields = clazz.getDeclaredFields();
        StringBuilder inserqtSql = new StringBuilder();
        inserqtSql.append("INSERT INTO ").append(getTableName(clazz)).append( " (");
        for (int i = 0; i < fields.length; i++) {
            Field field = fields[i];
            String columnName = getFieldName(field);
            inserqtSql.append(columnName);
            if (i < fields.length - 1) {
                inserqtSql.append(", ");
            }
        }
        inserqtSql.append(") VALUES (");
        for (int i = 0; i < fields.length; i++) {
            inserqtSql.append("?");
            if (i < fields.length - 1) {
                inserqtSql.append(", ");
            }
        }
        inserqtSql.append(")");
        return inserqtSql.toString();
    }

    public static String buildQueryFromClass(Class<?> clazz) {
        List<Field> fields = CGenericUtils.getAllFields(clazz);
        List<String> columns = new ArrayList<>();
        
        for (Field field : fields) {
            if (CGenericUtils.isFieldIgnored(field)) {
                continue;
            }
            columns.add(getFieldName(field));
        }
        
        if (columns.isEmpty()) {
            return "SELECT * FROM " + getTableName(clazz);
        }
        
        return "SELECT " + String.join(", ", columns) + " FROM " + getTableName(clazz);
    }

    public static Integer getClassIdValue(Object obj) {
        try {
            Method getIdMethod = obj.getClass().getMethod("getId");
            Object idValue = getIdMethod.invoke(obj);
            if (idValue instanceof Integer) {
                return (Integer) idValue;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    public static String getTableName(Class<?> clazz) {
        if (clazz.isAnnotationPresent(Table.class)) {
            Table tableAnnotation = clazz.getAnnotation(Table.class);
            if (!tableAnnotation.name().isEmpty()) {
                return tableAnnotation.name();
            }
        }
        return clazz.getSimpleName().toLowerCase();
    }

    public static String getFieldName(Field field){
        if(field.isAnnotationPresent(Column.class)){
            Column columnAnnotation = field.getAnnotation(Column.class);
            if(!columnAnnotation.name().isEmpty()){
                return columnAnnotation.name();
            }
            return toSnakeCase(field.getName());
        } else {
            return toSnakeCase(field.getName());
        }
    }

    private static String toSnakeCase(String name) {
        if (name == null || name.isEmpty()) {
            return name;
        }

        StringBuilder result = new StringBuilder();
        char[] chars = name.toCharArray();
        for (int i = 0; i < chars.length; i++) {
            char c = chars[i];
            if (Character.isUpperCase(c)) {
                if (i > 0 && chars[i - 1] != '_' && !Character.isUpperCase(chars[i - 1])) {
                    result.append('_');
                }
                result.append(Character.toLowerCase(c));
            } else {
                result.append(c);
            }
        }

        return result.toString();
    }

    private static String snakeToCamel(String name) {
        if (name == null || name.isEmpty()) {
            return name;
        }

        StringBuilder result = new StringBuilder();
        boolean toUpper = false;
        for (char c : name.toCharArray()) {
            if (c == '_') {
                toUpper = true;
                continue;
            }

            if (result.length() == 0) {
                result.append(Character.toLowerCase(c));
                toUpper = false;
                continue;
            }

            if (toUpper) {
                result.append(Character.toUpperCase(c));
                toUpper = false;
            } else {
                result.append(Character.toLowerCase(c));
            }
        }

        return result.toString();
    }
}
